---
- name: haproxy configure
  hosts: 192.168.0.144
  become: true
  tasks:
    - name: config /etc/sysctl.conf
      lineinfile:
        path: /etc/sysctl.conf
        line: "net.ipv4.ip_forward = 1"
        state: present

    - name: restart sysctl
      command: sysctl --system

    - name: install Firewalld
      apt:
        name: firewalld
        state: present

    - name: on Firewalld
      service:
        name: firewalld
        state: started
        enabled: yes

    - name: add zone cloude
      command: firewall-cmd --permanent --new-zone=cloude

    - name: add rule cloude
      command: firewall-cmd --permanent --zone=cloude --add-forward

    - name: add rule cloude
      command: firewall-cmd --permanent --zone=cloude --add-masquerade

    - name: add interface160 cloude
      command: firewall-cmd --permanent --zone=cloude --add-interface=ens160

    - name: add interface192 cloude
      command: firewall-cmd --permanent --zone=cloude --add-interface=ens192

    - name: add interface224 cloude
      command: firewall-cmd --permanent --zone=cloude --add-interface=ens224

    - name: add port 80/tcp
      command: firewall-cmd --permanent --zone=cloude --add-port=80/tcp
    
    - name: add port 80/udp
      command: firewall-cmd --permanent --zone=cloude --add-port=80/udp
  
    - name: add port 443/tcp
      command: firewall-cmd --permanent --zone=cloude --add-port=443/tcp
    
    - name: add port 443/udp
      command: firewall-cmd --permanent --zone=cloude --add-port=443/udp

    - name: add service http
      command: firewall-cmd --permanent --zone=cloude --add-service=http

    - name: add service https
      command: firewall-cmd --permanent --zone=cloude --add-service=https

    - name: restart firewalld
      service:
        name: firewalld
        state: restarted

    - name: install haproxy
      apt:
        name: haproxy
        state: present
        enabled: yes

    - name: config HAProxy
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        owner: root
        group: root
        mode: '0644'

    - name: restart
      service:
        name: haproxy
        state: restarted
